title: Error page
icon: alert

columns:
  - width: 1/2
    sections:
    fields:

      defaultHeadline:
        label: Error pagina tekst
        type: headline
      errorPageTitle:
        label: Titel
        type: text
        required: true
      errorPageParagraph:
        label: Paragraaf
        type: writer
        inline: true

