name: Services
icon: store
label: "| {{ servicestitle }}"
fields:
  services:
    extends: fields/services
    fields:
      servicesHeadline:
        numbered: false
      servicesSwitch: false
  line-z:
    type: line
  firstCta:
    extends: fields/firstCta
    fields:
      firstCtaHeadline:
        numbered: false
      firstCtaSwitch: false