title: Music2Move website

tabs:
  content:
    icon: dashboard

    columns:

      #pages
      - width: 1/3
        sections:
          listed:
            headline: Listed pages
            type: pages
            status: listed
          unlisted:
            headline: Unlisted pages
            type: pages
            status: unlisted
          drafts:
            headline: Pages in draft
            type: pages
            status: draft
      
      #text content
      - width: 2/3
        sections:
        fields:
          menuHeadline:
            label: Menu
            type: headline
            numbered: false
          navigationLinks:
            label: Menu items
            type: structure
            columns:
              anchor:
                width: 1/3
              page:
                width: 1/3
              section:
                width: 1/3
            fields:
              anchor:
                label: Anker
                type: text
              page:
                label: Pagina
                type: pages
              section:
                label: id op pagina
                type: text
          line-a:
            type: line

            
    
  logos:
    icon: image
    columns:

      - width: 1/3
        sections:
        fields:

          #logos
          logoLight:
            label: Licht logo
            type: files
            max: 1
            layout: cards
          logoDark:
            label: Donker logo
            type: files
            max: 1
            layout: cards