title: PO - Starter Kit

tabs:
  menu:
    icon: dashboard

    columns:

      #Pages
      - width: 1/3
        sections:
          listed:
            headline: Listed pages
            type: pages
            status: listed
          unlisted:
            headline: Unlisted pages
            type: pages
            status: unlisted
          drafts:
            headline: Pages in draft
            type: pages
            status: draft
      
      #text content
      - width: 2/3
        sections:
        fields:

          #Navigation
          menuHeadline:
            label: Navigatie
            type: headline
          navigationLinks:
            label: Menu items
            type: structure
            columns:
              anchor:
                width: 1/3
              page:
                width: 1/3
              section:
                width: 1/3
            fields:
              anchor:
                label: Anker*
                type: text
                required: true
                width: 1/2
              destination:
                label: Link naar
                type: toggle
                text: 
                  - "interne pagina"
                  - "externe url"
              page:
                label: Pagina*
                type: pages
                width: 1/2
                required: true
                when:
                  destination: false
              section:
                label: (Sectie op pagina)
                type: text
                width: 1/2
                when:
                  destination: false
              externalUrl:
                label: Externe URL*
                type: url
                required: true
                when:
                  destination: true
          ctaHeadline:
            label: Navigatie - CTA Button
            type: headline
            numbered: false
          ctaButton:
            label: Menu CTA
            extends: fields/button
            max: 1
          line-a:
            type: line


          #Logos
          logosHeadline:
            label: Logos
            type: headline
          logoDark:
            label: Logo - Standaard
            type: files
            max: 1
            layout: cards
            width: 1/2
            image:
              back: white
          logoLight:
            label: Logo - light
            type: files
            max: 1
            layout: cards
            back: black
            width: 1/2
            image:
              back: black



  contact:
    icon: email

    columns:

      - width: 1/4
        sections:
        fields:
          contactHeadline:
            label: Contactgegevens & sociale media
            type: headline
            numbered: false
      
      - width: 3/4
        sections:
        fields:

          #Contact
          contactInfoHeadline:
            label: Contactgegevens
            type: headline
          email:
            label: Email
            type: text
          telephone:
            label: Telefoonnummer
            type: text
          line-d:
            type: line

          #Socials
          socialsHeadline:
            label: Sociale media
            type: headline
          socials:
            label: Socials
            type: structure
            columns:
              social:
                width: 1/4
              url:
                width: 3/4
            fields:
              social:
                type: select
                options:
                  facebook: Facebook
                  instagram: Instagram
                  linkedin: LinkedIn
                  twitter: Twitter
              url:
                type: url
          


  footer:
    icon: grid-bottom

    columns:

      - width: 1/4
        sections:
        fields:
          footerHeadline:
            label: Footer
            type: headline
            numbered: false

      - width: 3/4
        sections:
        fields:
          #Footer
          footerIntroHeadline:
            label: Info over jouw organisatie
            type: headline
          infoIntro:
            label:
            type: info
            text: 2-3 zinnen over wat jouw organisatie doet.
            width: 1/2
          intro:
            label: Bedrijfsinformatie
            type: writer
            inline: true
          line-c:
            type: line

          sitemapHeadline:
            label: Sitemap
            type: headline
            numbered: true
          sitemap:
            label: Sitemap
            type: structure
            fields:
              anchor:
                label: Link text
                type: text
                required: true
              page:
                label: Pagina
                type: pages
                required: true
                max: 1
              section:
                label: Sectie op pagina
                type: text
  


  seotab: seo